FROM rabbitmq:3.6-management

COPY wait-for-it.sh /usr/local/bin/
COPY rabbitmq-init-for-maxwell.sh /usr/local/bin/
COPY rabbitmq-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["rabbitmq-entrypoint.sh", "rabbitmq-server"]